insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2008, null, null, null, null, null, null, null, null, null, null, null, null, 1.00, 1.00, null, null, 0.70, 2.00, 3.00, 300.00, null, 500.00, null, 10000.00, null, null, 2000.00, null, null, 800.00, 700.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2009, null, null, null, null, null, null, null, null, null, null, null, null, 2.00, 3.00, null, null, 0.90, 1.00, 3.00, 400.00, null, 600.00, null, 20000.00, null, null, 3000.00, null, null, 830.00, 740.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2010, null, null, null, null, null, null, null, null, null, null, null, null, -1.00, 2.00, null, null, 0.80, 1.00, -2.00, 500.00, null, 700.00, null, 30000.00, null, null, 4000.00, null, null, 800.00, 700.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2011, null, null, null, null, null, null, null, null, null, null, null, null, -3.00, 4.00, null, null, 0.40, 9.00, 11.00, 600.00, null, 800.00, null, 20000.00, null, null, -42300.00, null, null, 800.00, 700.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2012, null, null, null, null, null, null, null, null, null, null, null, null, 2.00, 4.00, null, null, 1.00, 2.00, 12.00, 700.00, null, 900.00, null, 10000.00, null, null, -3000.00, null, null, -800.00, -700.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2013, null, null, null, null, null, null, null, null, null, null, null, null, 1.00, 1.00, null, null, 1.00, 18.00, 12.00, 800.00, null, 1000.00, null, 20000.00, null, null, 7000.00, null, null, 800.00, 1700.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2014, null, null, null, null, null, null, null, null, null, null, null, null, 2.00, 2.00, null, null, 1.00, 56.00, 21.00, 900.00, null, 1000.00, null, 10000.00, null, null, 8000.00, null, null, 820.00, 700.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2015, null, null, null, null, null, null, null, null, null, null, null, null, 2.00, 3.00, null, null, 1.00, -10.00, -43.00, 100.00, null, 1000.00, null, 30000.00, null, null, -300.00, null, null, 1800.00, 750.00, null, '2016-07-12 15:45:03.0', null);
insert into investdata.t_balance_sheet (code, year, note_recable, adv_customers, acc_payable, constr_in_pro, lntang_assets, goodwill, short_term_loans, note_payable, debit_within_year, long_term_loans, bounds_payable, liquid_assets_start, liquid_assets_end, curr_liab, curr_liab_non, goods_start, goods_end, cash, trad_assets, total_liab, total_ass_start, total_ass_end, share_holder_start, share_holder_end, fixed_assets_start, fixed_assets_end, retain_earnings, acc_recable_start, acc_recable_end, capital_surplus, surplus_reserve, flag, intime, moduser) values ('000895', 2016, null, null, null, null, null, null, null, null, null, null, null, null, 16.00, 12.00, null, null, 3.00, 12.00, 11.00, 300.00, null, 1100.00, null, 11000.00, null, null, 10000.00, null, null, 870.00, 20.00, null, '2016-07-12 15:45:03.0', null);


insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2008, 700.00, 300.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2009, 740.00, -400.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2010, 700.00, -300.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2011, 700.00, -50.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2012, -700.00, 500.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2013, 1700.00, 550.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2014, 700.00, 600.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2015, 750.00, 700.00, null, '2016-07-06 15:14:15.0', null);
insert into investdata.t_cashflow_sheet (code, year, opera_active_cash, cash_and_cashequ, flag, intime, moduser) values ('000895', 2016, 20.00, 900.00, null, '2016-07-06 15:14:15.0', null);

insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2008, 100, null, null, null, 23.50, 21.50, null, '2016-07-05 17:53:05.0', '');
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2009, 200, null, null, null, 15.30, 15.00, null, '2016-07-05 17:53:05.0', null);
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2010, 300, null, null, null, 17.30, 15.90, null, '2016-07-05 17:53:05.0', null);
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2011, 400, null, null, null, 19.30, -1.00, null, '2016-07-05 17:53:05.0', null);
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2012, 500, null, null, null, 29.30, 23.00, null, '2016-07-05 17:53:05.0', null);
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2013, 550, null, null, null, -19.30, -15.00, null, '2016-07-05 17:53:05.0', null);
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2014, 600, null, null, null, 34.30, 25.00, null, '2016-07-05 17:53:05.0', null);
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2015, 700, null, null, null, 24.30, 21.00, null, '2016-07-05 17:53:05.0', null);
insert into investdata.t_gendata_sheet (code, year, total_stocks, roe_wa, roe_wa_kf, dividen_pay_sum, eps, eps_diluted, flag, intime, moduser) values ('000895', 2016, 700, null, null, null, 21.30, 10.96, null, '2016-07-05 17:53:05.0', null);


insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2008, 1500.00, 1500.00, 1100.00, null, null, null, null, null, 10000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, 1500.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2009, 1600.00, 1600.00, 1300.00, null, null, null, null, null, 20000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, 2500.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2010, 1800.00, 1800.00, 1200.00, null, null, null, null, null, 40000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, 300.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2011, 1500.00, 1500.00, 100.00, null, null, null, null, null, 30000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, -400.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2012, 1000.00, 1000.00, -800.00, null, null, null, null, null, 50000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, -200.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2013, -50.00, -50.00, -900.00, null, null, null, null, null, 80000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, -100.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2014, -1150.00, -1150.00, -1150.00, null, null, null, null, null, 100000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, 4000.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2015, 700.00, 700.00, 100.00, null, null, null, null, null, 110000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, 1200.00);
insert into investdata.t_incstate_sheet (code, year, busi_income_this, busi_income_last, opera_profits_this, opera_profits_last, income_tax, fixed_ass_depre, long_pre_amort, total_profit_start, total_profit_end, market_consts_this, market_consts_last, finance_consts_this, finance_consts_last, mgr_consts_this, mgr_consts_last, busi_tax_surcharge, net_profits_this, net_profits_last, net_profits_kf_last, net_profits_kf_this, operat_cost, busi_income_kf, fair_val_change, invest_income, non_opera_income, non_opera_outcome, flag, intime, moduser, inter_expense) values ('000895', 2016, 900.00, 900.00, 2000.00, null, null, null, null, null, 120000.00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2016-07-06 17:08:49.0', null, 3000.00);





